//import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import './globals.css';
import { Inter } from 'next/font/google';
import Link from 'next/link'; 

const inter = Inter({ subsets: ['latin'] });

export default function RootLayout({ children }) {
  return (
    <html lang="es"> 
      <body className={inter.className}>
        <nav className="navbar navbar-expand-lg navbar-light bg-light">
          <div className="container">
            <Link className="navbar-brand" href="/">Mi Blog</Link> {/* Link con mayúscula y espacio */}
            <div className="navbar-nav">
              <Link className="nav-link" href="/about">Acerca de</Link>
              <Link className="nav-link" href="/posts">Posts</Link>
              <Link className="nav-link" href="/contact">Contacto</Link>
            </div>
          </div>
        </nav>
        <div className="container mt-4">
          {children}
        </div>
      </body>
    </html>
  );
}

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

/*export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );*/

